version: '2'
services:

    #Problemas con mysql
  mysql:
    container_name: mysql 
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: '' 
    ports:
      - "3306:3306"
    volumes:
      - ./dat /var/lib/mysql 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 


  php:
    container_name: php
    restart: always
    image: ualmtorres/phalcon-apache-ubuntu
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html